service: auth-service
frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:ListBucket'
          Resource:
            'Fn::Join':
              - ''
              - - 'arn:aws:s3:::'
                - Ref: ServerlessDeploymentBucket
        - Effect: Allow
          Action:
            - 's3:PutObject'
          Resource:
            'Fn::Join':
              - ''
              - - 'arn:aws:s3:::'
                - Ref: ServerlessDeploymentBucket
                - /*
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
  environment:  ${file(./configs/variable/env.yml)}
plugins:
  - serverless-offline
functions:

  authorizer:
    handler: handlers/authorizer.auth
    events:
      - httpApi:
        path: /auth
        method: get

        
  hello:
    handler: handlers/auth-handler.hello
    events:
      - httpApi:
          path: /getProduct
          method: get

  postData:
    handler: handlers/product-post.postData
    events:
      - httpApi:
          path: /product
          method: POST

  

resources:
  - ${file(./configs/resources/dynamo.yml)}
