service: auth-service
frameworkVersion: '3'

custom:
  productTableName: my-product-table-dev


provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:ListBucket'
          Resource:
            'Fn::Join':
              - ''
              - - 'arn:aws:s3:::'
                - Ref: ServerlessDeploymentBucket
        - Effect: Allow
          Action:
            - 's3:PutObject'
          Resource:
            'Fn::Join':
              - ''
              - - 'arn:aws:s3:::'
                - Ref: ServerlessDeploymentBucket
                - /*
plugins:
  - serverless-offline
functions:
  hello:
    handler: handlers/auth-handler.hello
    events:
      - httpApi:
          path: /users
          method: get

resources:
  - ${file(./configs/resources/dynamo.yml)}
