service: auth-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:ListBucket"
          Resource:
            "Fn::Join":
              - ""
              - - "arn:aws:s3:::"
                - Ref: ServerlessDeploymentBucket
        - Effect: Allow
          Action:
            - "s3:PutObject"
          Resource:
            "Fn::Join":
              - ""
              - - "arn:aws:s3:::"
                - Ref: ServerlessDeploymentBucket
                - /*
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
  environment: ${file(./configs/variable/env.yml)}
plugins:
  - serverless-offline
functions:
  custom-authorizer:
    handler: handlers/authorizer.auth

  hello:
    handler: handlers/auth-handler.hello
    events:
      - http:
          path: /getProduct
          method: get
          authorizer:
            name: custom-authorizer
            type: request
            identitySource: method.request.header.my-token

  postData:
    handler: handlers/product-post.postData
    events:
      - http:
          path: /product
          method: POST
          authorizer:
            name: custom-authorizer
            type: request
            identitySource: method.request.header.my-token

resources:
  - ${file(./configs/resources/dynamo.yml)}
